name: primer workflow 

on: [push]

jobs: 
    build: 
        runs-on: ubuntu-latest
    
        steps:
        - name: echo a string
          run: | 
                echo "hola mundo"
                pwd
                ls
                